#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

#include "XamlBindingInfo.g.h"

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBlock;
                ref class ListView;
                ref class GridView;
            }
        }
    }
}

namespace Opal
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class SearchPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class SearchPage_obj5_Bindings;
        class SearchPage_obj12_Bindings;
        class SearchPage_obj18_Bindings;
        class SearchPage_obj1_Bindings;
    
        ::XamlBindingInfo::XamlBindings^ Bindings;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ SearchHeader;
        private: ::Windows::UI::Xaml::Controls::ListView^ SongsListView;
        private: ::Windows::UI::Xaml::Controls::GridView^ AlbumsGridView;
        private: ::Windows::UI::Xaml::Controls::GridView^ ArtistsGridView;
    };
}

